global:
  scrape_interval: 60s
  external_labels:
    origin_prometheus: prometheus01

remote_write:
  - url: https://prometheus-prod-24-prod-eu-west-2.grafana.net/api/prom/push
    basic_auth:
      username: ${GRAFANA_CLOUD_USERNAME}
      password: ${GRAFANA_CLOUD_API_KEY}

scrape_configs:
  - job_name: node
    static_configs:
      - targets: [ "localhost:9090" ]
