#!/bin/bash

cd /var/www/rokis-corner
git pull origin main
source venv/bin/activate
pip install -r requirements.txt
python manage.py migrate
python manage.py collectstatic --noinput
sudo systemctl restart rokis-corner.gunicorn
