# Generated by Django 5.1 on 2024-08-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('filename', models.CharField(max_length=100, verbose_name='filename')),
                ('avatar', models.ImageField(null=True, upload_to='cv/img/', verbose_name='avatar')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('role', models.CharField(max_length=100, verbose_name='role')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('address_label', models.CharField(max_length=100, verbose_name='address label')),
                ('address_link', models.URLField(max_length=1000, verbose_name='address link')),
                ('about_me', models.TextField(verbose_name='about me')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
            },
        ),
    ]
