# Generated by Django 5.1 on 2024-08-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('website', 'Website')], max_length=10, verbose_name='type'),
        ),
    ]
