# Generated by Django 5.1 on 2024-08-26 16:52

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='is published'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='avatar',
            field=models.ImageField(null=True, upload_to='cv/img/', validators=[common.validators.MaxFileSizeValidator(100)], verbose_name='avatar'),
        ),
    ]
