# Generated by Django 5.1 on 2024-08-18 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_skill_options_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employment',
            options={'default_related_name': 'employments', 'verbose_name': 'Employment', 'verbose_name_plural': 'Employments'},
        ),
        migrations.AlterField(
            model_name='employment',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv', verbose_name='CV'),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('company', models.CharField(max_length=100, verbose_name='company')),
                ('start', models.DateField(help_text="Day is not important. Select 1st if you don't know the exact start day.", verbose_name='start')),
                ('end', models.DateField(blank=True, help_text="Leave empty if you are currently working here. Day is not important. Select 1st if you don't know the exact end day.", null=True, verbose_name='end')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('description', models.TextField(verbose_name='description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Internship',
                'verbose_name_plural': 'Internships',
                'default_related_name': 'internships',
            },
        ),
    ]
