# Generated by Django 5.1 on 2024-08-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_employment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub')], max_length=10, verbose_name='type')),
                ('label', models.CharField(max_length=100, verbose_name='label')),
                ('url', models.URLField(verbose_name='URL')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
    ]
