# Generated by Django 5.1 on 2024-08-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_employment_options_alter_employment_cv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='school')),
                ('degree', models.CharField(max_length=100, verbose_name='degree')),
                ('start', models.DateField(help_text="Day is not important. Select 1st if you don't know the exact start day.", verbose_name='start')),
                ('end', models.DateField(blank=True, help_text="Leave empty if you are currently studying here. Day is not important. Select 1st if you don't know the exact end day.", null=True, verbose_name='end')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
                ('description', models.TextField(verbose_name='description')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.cv', verbose_name='CV')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
    ]
